spring.application.name=main
server.port=8090
logging.level.org.thymeleaf=DEBUG

# Configuración de internacionalización
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.web.locale-resolver=fixed
spring.web.locale=es

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/cpp?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Tiempo máximo de sesión por inactividad
server.servlet.session.timeout=1m